### ISSUE TITLE
datatype for ttl can be smallint instead of bigint

### ISSUE THREAD

**Issue by sravankumar777** [cloudfoundry/locket#6]
**Suggestion**
Currently, datatype for ttl(time to live for lock) is bigint.
Generally, this value shall not be exceeding more than 32767(smallint data range(```-32768 to +32767```)).

So syntatically, we can use this datatype for ttl, instead of bigint(```-9223372036854775808 to +9223372036854775807```).

Please check.

**Comment by emalm** [comment]
@sravankumar777 I don't know, maybe some set of clients would want to contend over day-long leases on a lock, which would use a TTL of 86,400 seconds. What problems is having this column type be a bigint causing you?

Thanks,
Eric, CF Diego PM

**Comment by sravankumar777** [comment]
Thanks Eric for your reply.

It was a suggestion from my side to have smallinteger.
We dont have any issue observed with this.
I was in opinion that, usually ttl value preferred to less value than 32767. 
So, instead of having bigint datatype for ttl. We could have used smallinteger only.

**Comment by emalm** [comment]
Thanks, @sravankumar777. Given that it's not causing any particular problems, we'll plan to leave it as a `bigint`. Probably a plain old 32-bit `int` would have been a better compromise, though.
