### ISSUE TITLE
 "sql: no rows in result set" in logs when using postgres 

### ISSUE THREAD

**Issue by scottillogical** [cloudfoundry/locket#8]
Hey Locket team,

We are using diego 2.0 (working on upgrading) with an off box bosh postgres. This is on postgres  9.5.1 (but we run 9.6 and 10 in other places) haven't checked the logs there yet

```{"timestamp":"1546892100.616996765","source":"locket","message":"locket.lock.lock.acquired-lock","log_level":1,"data":{"key":"80d7f544-1cdb-4d19-a0f7-fcb6bf18e8ae","owner":"e5bccfa1-4efb-4acc-7a80-cdd51b7bfd35","session":"497.1","type":"presence","type-code":2}}
{"timestamp":"1546892149.063099623","source":"locket","message":"locket.release.release-lock.released-lock","log_level":1,"data":{"key":"96ed92b3-97a3-410a-b001-cadda88af2cb","owner":"083cbd16-68d8-4cd5-72e6-49596319abe5","session":"637.1","type":"presence","type-code":2}}
{"timestamp":"1546892162.310873270","source":"locket","message":"locket.lock.register-ttl.fetch-and-release-lock.failed-to-fetch-lock","log_level":2,"data":{"error":"sql: no rows in result set","key":"96ed92b3-97a3-410a-b001-cadda88af2cb","modified-index":622,"owner":"083cbd16-68d8-4cd5-72e6-49596319abe5","session":"632.2.1","type":"presence","type-code":2}}
```

I'm not aware of this causing any trouble specifically but was wondering if this was something that should be looked into, thanks!

**Comment by emalm** [comment]
Thanks, @scottschulthess ! At first glance, I'm inclined to think it's not a sign of a real failure: I think that it's this Locket instance trying to clean up an expired lock after that lock was released deliberately. Even so, we don't want Locket to be logging error-level messages for behavior that's not anomalous. We on the Diego team will take a closer look at these and related logs soon to see if we can improve the signal-to-noise ratio around lock-expirations.

Best,
Eric
