### ISSUE TITLE
Cert expiry or misconfiguration can cause useless error messages

### ISSUE THREAD

**Issue by cwlbraa** [cloudfoundry/locket#9]
Observed as follows when cloudfoundry/bbs is failing to start after a certificate rotation that we haven't handled perfectly correctly. 

```
{"timestamp":"2019-06-27T17:28:56.734523548Z","level":"fatal","source":"bbs","message":"bbs.failed-to-create-locket-client","data":{"error":"context deadline exceeded","trace":"goroutine 1 [running]:\ncode.cloudfoundry.org/lager.(*logger).Fatal(0xc0000a2840, 0xcdcc58, 0x1e, 0xdc4120, 0x13a47e0, 0x0, 0x0, 0x0)\n\t/var/vcap/data/compile/bbs/src/code.cloudfoundry.org/lager/logger.go:138 +0xc6\nmain.main()\n\t/var/vcap/data/compile/bbs/src/code.cloudfoundry.org/bbs/cmd/bbs/main.go:239 +0x41d4\n"}}
```

It'd be great if this errored so that it was obvious where we've gone wrong. 

https://github.com/cloudfoundry/bbs/blob/6422875042feac096549a05298a4c6f005519290/cmd/bbs/main.go#L239
https://github.com/cloudfoundry/locket/blob/285105ed8d9a2c4bae7002b0cb5eb35e7e1b6cd7/locket_client.go#L60

**Comment by heyjcollins** [comment]
closing this out as it's unlikely we'll take any action to resolve it.
